//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://localhost//WebServices//")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost//WebServices//", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://localhost//WebServices// 的元素名称 s 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//WebServices//StudentScore", ReplyAction="*")]
        TestApp.ServiceReference1.StudentScoreResponse StudentScore(TestApp.ServiceReference1.StudentScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost//WebServices//StudentScore", ReplyAction="*")]
        System.Threading.Tasks.Task<TestApp.ServiceReference1.StudentScoreResponse> StudentScoreAsync(TestApp.ServiceReference1.StudentScoreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentScore", Namespace="http://localhost//WebServices//", Order=0)]
        public TestApp.ServiceReference1.StudentScoreRequestBody Body;
        
        public StudentScoreRequest() {
        }
        
        public StudentScoreRequest(TestApp.ServiceReference1.StudentScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost//WebServices//")]
    public partial class StudentScoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestApp.ServiceReference1.Student s;
        
        public StudentScoreRequestBody() {
        }
        
        public StudentScoreRequestBody(TestApp.ServiceReference1.Student s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StudentScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StudentScoreResponse", Namespace="http://localhost//WebServices//", Order=0)]
        public TestApp.ServiceReference1.StudentScoreResponseBody Body;
        
        public StudentScoreResponse() {
        }
        
        public StudentScoreResponse(TestApp.ServiceReference1.StudentScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost//WebServices//")]
    public partial class StudentScoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentScoreResult;
        
        public StudentScoreResponseBody() {
        }
        
        public StudentScoreResponseBody(string StudentScoreResult) {
            this.StudentScoreResult = StudentScoreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TestApp.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TestApp.ServiceReference1.WebService1Soap>, TestApp.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestApp.ServiceReference1.StudentScoreResponse TestApp.ServiceReference1.WebService1Soap.StudentScore(TestApp.ServiceReference1.StudentScoreRequest request) {
            return base.Channel.StudentScore(request);
        }
        
        public string StudentScore(TestApp.ServiceReference1.Student s) {
            TestApp.ServiceReference1.StudentScoreRequest inValue = new TestApp.ServiceReference1.StudentScoreRequest();
            inValue.Body = new TestApp.ServiceReference1.StudentScoreRequestBody();
            inValue.Body.s = s;
            TestApp.ServiceReference1.StudentScoreResponse retVal = ((TestApp.ServiceReference1.WebService1Soap)(this)).StudentScore(inValue);
            return retVal.Body.StudentScoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestApp.ServiceReference1.StudentScoreResponse> TestApp.ServiceReference1.WebService1Soap.StudentScoreAsync(TestApp.ServiceReference1.StudentScoreRequest request) {
            return base.Channel.StudentScoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestApp.ServiceReference1.StudentScoreResponse> StudentScoreAsync(TestApp.ServiceReference1.Student s) {
            TestApp.ServiceReference1.StudentScoreRequest inValue = new TestApp.ServiceReference1.StudentScoreRequest();
            inValue.Body = new TestApp.ServiceReference1.StudentScoreRequestBody();
            inValue.Body.s = s;
            return ((TestApp.ServiceReference1.WebService1Soap)(this)).StudentScoreAsync(inValue);
        }
    }
}
